#!/usr/bin/env bash

# Simple note-taking script
# Author Anthony Ledesma

# Get the date
date=$(date);

# Get the topic
topic=$1;
# Ask user for input
read -p "Your note: " note;

echo $date: $note >> ~/${topic}notes.txt;
echo "Note saved: $note";

