#!/usr/bin/env bash

# Simple note-taking script
# Author Anthony Ledesma

# Get the date
date=$(date);

# Get the topic
topic="$1";

# Set filename
filename="${HOME}/${topic}notes.txt";

# Ask user for input
read -p "Your note: " note;

echo "$date: $note" >> "$filename";
echo "Note '$note' saved to '$filename'";

