#!/usr/bin/env bash

#for i in $(ls); do
	#if( ls $i | grep "(.mp3){1}" -Pi)
	#then
	#mv $i "$(date +%F)-$i"
	#echo processed item: $i	

	#fi

DIR=$(pwd)
[ $# -eq 0 ] && DIR=$(pwd) && echo "No Directory Given. Defaulting to pwd: $(pwd)" || DIR=$1 && echo "Directory has been given. Dir: $1"
[ -d "$DIR" ] && cd "$DIR" || exit 1

shopt -s nullglob
found=0
for i in *.mp3; do
	echo "file $i found" 
	found=1
done
shopt -u nullglob
[ $found -eq 0 ] && echo "Directory is empty"
cd "$DIR"

#done

